sudo: required
services:
  - docker

before_install: 
  - docker build -t cursedwolf/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run cursedwolf/react-test npm test -- --coverage

after_success:
  - docker build -t cursedwolf/multi-client ./client
  - docker build -t cursedwolf/multi-nginx ./nginx
  - docker build -t cursedwolf/multi-server ./server
  - docker build -t cursedwolf/multi-worker ./worker
  #Login to docker-cli Taking images and pushing to hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cursedwolf/multi-client
  - docker push cursedwolf/multi-nginx
  - docker push cursedwolf/multi-server
  - docker push cursedwolf/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-000052450482
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
